import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/ui/components/navbar";
import Footer from '@/ui/components/footer';
import {montserrat} from '@/ui/fonts';



export const metadata: Metadata = {
  title: "Grupo Eusse",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-auto">
      <body
        className={` ${montserrat.className} antialiased min-h-screen flex flex-col bg-brand-50`}
        suppressHydrationWarning
      >
        <Navbar/>
        <main className="flex-1 flex flex-col">
          {children}
        </main>
        <Footer />
      </body>
      
    </html>
  );
}
